### ISSUE TITLE
index.js中有一段代码不太明白？

### ISSUE THREAD

**Issue by zeroone001** [nswbmw/koa-frouter#5]
`return function* frouter(next) {
    yield* next;
  };`
在里面起的作用是什么？

**Comment by nswbmw** [comment]
可以：

```
router(app, options)
```

也可以：

```
app.use(router(app, options))
```

**Comment by zeroone001** [comment]
@nswbmw  谢谢，但是起这个作用的原理，或者原因，不太明白

**Comment by nswbmw** [comment]
因为 app.use 需要一个 generatorFunction 啊，所以我们 return 一个就好了

**Comment by zeroone001** [comment]
明白了，谢谢
